version: "3.3"

services:
  postgres:
    build:
      context: ./postgres
    ports:
      - "5432:5432"


  web:
    build:
      context: ./client
    ports: 
    - '81:80'

volumes:
   db-data: {}