apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeserver
  labels:
    app: nodeserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeserver
  template:
    metadata:
      labels:
        app: nodeserver
    spec:
      containers:
      - name: nodeserver
        image: tomlecollegue/serverkart:v1.0.0
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: nodeserver-service
spec:
  type: LoadBalancer
  selector:
    app: nodeserver
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001
